// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD0
typedef void (*UniffiCallbackInterfaceBleGossipBroadcasterMethod0)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD1
typedef void (*UniffiCallbackInterfaceBleGossipBroadcasterMethod1)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD2
typedef void (*UniffiCallbackInterfaceBleGossipBroadcasterMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD3
typedef void (*UniffiCallbackInterfaceBleGossipBroadcasterMethod3)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER_METHOD4
typedef void (*UniffiCallbackInterfaceBleGossipBroadcasterMethod4)(uint64_t, uint8_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER_METHOD0
typedef void (*UniffiCallbackInterfaceBleGossipScannerMethod0)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER_METHOD1
typedef void (*UniffiCallbackInterfaceBleGossipScannerMethod1)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER_METHOD2
typedef void (*UniffiCallbackInterfaceBleGossipScannerMethod2)(uint64_t, void*_Nonnull, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLOB_DATA_RESPONDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLOB_DATA_RESPONDER_METHOD0
typedef void (*UniffiCallbackInterfaceBlobDataResponderMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLOB_DATA_RESPONDER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_BLOB_DATA_RESPONDER_METHOD1
typedef void (*UniffiCallbackInterfaceBlobDataResponderMethod1)(uint64_t, RustBuffer* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DEVICE_API_SERVICE_PROVIDER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DEVICE_API_SERVICE_PROVIDER_METHOD0
typedef void (*UniffiCallbackInterfaceDeviceApiServiceProviderMethod0)(uint64_t, void*_Nonnull* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_DEVICE_API_SERVICE_PROVIDER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_DEVICE_API_SERVICE_PROVIDER_METHOD1
typedef void (*UniffiCallbackInterfaceDeviceApiServiceProviderMethod1)(uint64_t, void*_Nonnull* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD0
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod0)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD1
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod1)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD2
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod2)(uint64_t, int8_t, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD3
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod3)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD4
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod4)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD5
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod5)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD6
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod6)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL_METHOD7
typedef void (*UniffiCallbackInterfaceGlobalViewModelMethod7)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOAD_COLLECTION_DELEGATE_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_LOAD_COLLECTION_DELEGATE_METHOD0
typedef void (*UniffiCallbackInterfaceLoadCollectionDelegateMethod0)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BLE_GOSSIP_BROADCASTER
typedef struct UniffiVTableCallbackInterfaceBleGossipBroadcaster {
    UniffiCallbackInterfaceBleGossipBroadcasterMethod0 _Nonnull start;
    UniffiCallbackInterfaceBleGossipBroadcasterMethod1 _Nonnull stop;
    UniffiCallbackInterfaceBleGossipBroadcasterMethod2 _Nonnull setDocumentData;
    UniffiCallbackInterfaceBleGossipBroadcasterMethod3 _Nonnull setAddressData;
    UniffiCallbackInterfaceBleGossipBroadcasterMethod4 _Nonnull setPeerState;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceBleGossipBroadcaster;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BLE_GOSSIP_SCANNER
typedef struct UniffiVTableCallbackInterfaceBleGossipScanner {
    UniffiCallbackInterfaceBleGossipScannerMethod0 _Nonnull startScanning;
    UniffiCallbackInterfaceBleGossipScannerMethod1 _Nonnull stopScanning;
    UniffiCallbackInterfaceBleGossipScannerMethod2 _Nonnull setDelegate;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceBleGossipScanner;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BLOB_DATA_RESPONDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_BLOB_DATA_RESPONDER
typedef struct UniffiVTableCallbackInterfaceBlobDataResponder {
    UniffiCallbackInterfaceBlobDataResponderMethod0 _Nonnull update;
    UniffiCallbackInterfaceBlobDataResponderMethod1 _Nonnull hash;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceBlobDataResponder;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DEVICE_API_SERVICE_PROVIDER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_DEVICE_API_SERVICE_PROVIDER
typedef struct UniffiVTableCallbackInterfaceDeviceApiServiceProvider {
    UniffiCallbackInterfaceDeviceApiServiceProviderMethod0 _Nonnull bleScanner;
    UniffiCallbackInterfaceDeviceApiServiceProviderMethod1 _Nonnull bleBroadcaster;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceDeviceApiServiceProvider;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_GLOBAL_VIEW_MODEL
typedef struct UniffiVTableCallbackInterfaceGlobalViewModel {
    UniffiCallbackInterfaceGlobalViewModelMethod0 _Nonnull nameUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod1 _Nonnull picUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod2 _Nonnull scanningUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod3 _Nonnull nearbyProfilesUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod4 _Nonnull statusUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod5 _Nonnull debugStateUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod6 _Nonnull allMessagesUpdated;
    UniffiCallbackInterfaceGlobalViewModelMethod7 _Nonnull receivedOneMessage;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceGlobalViewModel;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOAD_COLLECTION_DELEGATE
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_LOAD_COLLECTION_DELEGATE
typedef struct UniffiVTableCallbackInterfaceLoadCollectionDelegate {
    UniffiCallbackInterfaceLoadCollectionDelegateMethod0 _Nonnull update;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceLoadCollectionDelegate;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_APPHOST
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_APPHOST
void*_Nonnull uniffi_libgossip_fn_clone_apphost(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_APPHOST
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_APPHOST
void uniffi_libgossip_fn_free_apphost(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CONSTRUCTOR_APPHOST_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CONSTRUCTOR_APPHOST_NEW
void*_Nonnull uniffi_libgossip_fn_constructor_apphost_new(RustBuffer config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_BLOBS
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_BLOBS
void*_Nonnull uniffi_libgossip_fn_method_apphost_blobs(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_GLOBAL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_GLOBAL
void*_Nonnull uniffi_libgossip_fn_method_apphost_global(void*_Nonnull ptr, void*_Nonnull view_model, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_SET_RESET_FLAG
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_SET_RESET_FLAG
void uniffi_libgossip_fn_method_apphost_set_reset_flag(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_APPHOST_SHUTDOWN
void uniffi_libgossip_fn_method_apphost_shutdown(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLEGOSSIPBROADCASTER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLEGOSSIPBROADCASTER
void*_Nonnull uniffi_libgossip_fn_clone_blegossipbroadcaster(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLEGOSSIPBROADCASTER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLEGOSSIPBROADCASTER
void uniffi_libgossip_fn_free_blegossipbroadcaster(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_BLEGOSSIPBROADCASTER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_BLEGOSSIPBROADCASTER
void uniffi_libgossip_fn_init_callback_vtable_blegossipbroadcaster(UniffiVTableCallbackInterfaceBleGossipBroadcaster* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_START
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_START
void uniffi_libgossip_fn_method_blegossipbroadcaster_start(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_STOP
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_STOP
void uniffi_libgossip_fn_method_blegossipbroadcaster_stop(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_SET_DOCUMENT_DATA
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_SET_DOCUMENT_DATA
void uniffi_libgossip_fn_method_blegossipbroadcaster_set_document_data(void*_Nonnull ptr, RustBuffer document_data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_SET_ADDRESS_DATA
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_SET_ADDRESS_DATA
void uniffi_libgossip_fn_method_blegossipbroadcaster_set_address_data(void*_Nonnull ptr, RustBuffer address_data, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_SET_PEER_STATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPBROADCASTER_SET_PEER_STATE
void uniffi_libgossip_fn_method_blegossipbroadcaster_set_peer_state(void*_Nonnull ptr, uint8_t peer_state, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLEGOSSIPSCANNER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLEGOSSIPSCANNER
void*_Nonnull uniffi_libgossip_fn_clone_blegossipscanner(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLEGOSSIPSCANNER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLEGOSSIPSCANNER
void uniffi_libgossip_fn_free_blegossipscanner(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_BLEGOSSIPSCANNER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_BLEGOSSIPSCANNER
void uniffi_libgossip_fn_init_callback_vtable_blegossipscanner(UniffiVTableCallbackInterfaceBleGossipScanner* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPSCANNER_START_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPSCANNER_START_SCANNING
void uniffi_libgossip_fn_method_blegossipscanner_start_scanning(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPSCANNER_STOP_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPSCANNER_STOP_SCANNING
void uniffi_libgossip_fn_method_blegossipscanner_stop_scanning(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPSCANNER_SET_DELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLEGOSSIPSCANNER_SET_DELEGATE
void uniffi_libgossip_fn_method_blegossipscanner_set_delegate(void*_Nonnull ptr, void*_Nonnull delegate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLOBDATADISPATCHER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLOBDATADISPATCHER
void*_Nonnull uniffi_libgossip_fn_clone_blobdatadispatcher(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLOBDATADISPATCHER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLOBDATADISPATCHER
void uniffi_libgossip_fn_free_blobdatadispatcher(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLOBDATADISPATCHER_HYDRATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLOBDATADISPATCHER_HYDRATE
void uniffi_libgossip_fn_method_blobdatadispatcher_hydrate(void*_Nonnull ptr, void*_Nonnull bdr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLOBDATARESPONDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_BLOBDATARESPONDER
void*_Nonnull uniffi_libgossip_fn_clone_blobdataresponder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLOBDATARESPONDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_BLOBDATARESPONDER
void uniffi_libgossip_fn_free_blobdataresponder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_BLOBDATARESPONDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_BLOBDATARESPONDER
void uniffi_libgossip_fn_init_callback_vtable_blobdataresponder(UniffiVTableCallbackInterfaceBlobDataResponder* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLOBDATARESPONDER_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLOBDATARESPONDER_UPDATE
void uniffi_libgossip_fn_method_blobdataresponder_update(void*_Nonnull ptr, RustBuffer state, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLOBDATARESPONDER_HASH
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_BLOBDATARESPONDER_HASH
RustBuffer uniffi_libgossip_fn_method_blobdataresponder_hash(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_DEVICEAPISERVICEPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_DEVICEAPISERVICEPROVIDER
void*_Nonnull uniffi_libgossip_fn_clone_deviceapiserviceprovider(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_DEVICEAPISERVICEPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_DEVICEAPISERVICEPROVIDER
void uniffi_libgossip_fn_free_deviceapiserviceprovider(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_DEVICEAPISERVICEPROVIDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_DEVICEAPISERVICEPROVIDER
void uniffi_libgossip_fn_init_callback_vtable_deviceapiserviceprovider(UniffiVTableCallbackInterfaceDeviceApiServiceProvider* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_DEVICEAPISERVICEPROVIDER_BLE_SCANNER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_DEVICEAPISERVICEPROVIDER_BLE_SCANNER
void*_Nonnull uniffi_libgossip_fn_method_deviceapiserviceprovider_ble_scanner(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_DEVICEAPISERVICEPROVIDER_BLE_BROADCASTER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_DEVICEAPISERVICEPROVIDER_BLE_BROADCASTER
void*_Nonnull uniffi_libgossip_fn_method_deviceapiserviceprovider_ble_broadcaster(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GLOBAL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GLOBAL
void*_Nonnull uniffi_libgossip_fn_clone_global(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GLOBAL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GLOBAL
void uniffi_libgossip_fn_free_global(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_LOAD_NEARBY_PAYLOAD
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_LOAD_NEARBY_PAYLOAD
uint64_t uniffi_libgossip_fn_method_global_load_nearby_payload(void*_Nonnull ptr, RustBuffer hash, void*_Nonnull collection_delegate
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SEND_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SEND_MESSAGE
uint64_t uniffi_libgossip_fn_method_global_send_message(void*_Nonnull ptr, RustBuffer text, RustBuffer payload_dir
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_NAME
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_NAME
uint64_t uniffi_libgossip_fn_method_global_set_name(void*_Nonnull ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_PIC
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_PIC
uint64_t uniffi_libgossip_fn_method_global_set_pic(void*_Nonnull ptr, RustBuffer pic_data
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_SCANNING
uint64_t uniffi_libgossip_fn_method_global_set_scanning(void*_Nonnull ptr, int8_t should_scan
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_STATUS
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBAL_SET_STATUS
uint64_t uniffi_libgossip_fn_method_global_set_status(void*_Nonnull ptr, RustBuffer status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GLOBALVIEWMODEL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GLOBALVIEWMODEL
void*_Nonnull uniffi_libgossip_fn_clone_globalviewmodel(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GLOBALVIEWMODEL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GLOBALVIEWMODEL
void uniffi_libgossip_fn_free_globalviewmodel(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_GLOBALVIEWMODEL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_GLOBALVIEWMODEL
void uniffi_libgossip_fn_init_callback_vtable_globalviewmodel(UniffiVTableCallbackInterfaceGlobalViewModel* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_NAME_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_NAME_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_name_updated(void*_Nonnull ptr, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_PIC_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_PIC_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_pic_updated(void*_Nonnull ptr, RustBuffer pic
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_SCANNING_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_SCANNING_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_scanning_updated(void*_Nonnull ptr, int8_t scanning
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_NEARBY_PROFILES_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_NEARBY_PROFILES_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_nearby_profiles_updated(void*_Nonnull ptr, RustBuffer profiles
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_STATUS_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_STATUS_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_status_updated(void*_Nonnull ptr, RustBuffer status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_DEBUG_STATE_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_DEBUG_STATE_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_debug_state_updated(void*_Nonnull ptr, RustBuffer status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_ALL_MESSAGES_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_ALL_MESSAGES_UPDATED
uint64_t uniffi_libgossip_fn_method_globalviewmodel_all_messages_updated(void*_Nonnull ptr, RustBuffer messages
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_RECEIVED_ONE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GLOBALVIEWMODEL_RECEIVED_ONE_MESSAGE
uint64_t uniffi_libgossip_fn_method_globalviewmodel_received_one_message(void*_Nonnull ptr, RustBuffer message
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GOSSIPERROR
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GOSSIPERROR
void*_Nonnull uniffi_libgossip_fn_clone_gossiperror(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GOSSIPERROR
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GOSSIPERROR
void uniffi_libgossip_fn_free_gossiperror(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GOSSIPSCANNERDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_GOSSIPSCANNERDELEGATE
void*_Nonnull uniffi_libgossip_fn_clone_gossipscannerdelegate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GOSSIPSCANNERDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_GOSSIPSCANNERDELEGATE
void uniffi_libgossip_fn_free_gossipscannerdelegate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GOSSIPSCANNERDELEGATE_PEER_DATA_DISCOVERED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_GOSSIPSCANNERDELEGATE_PEER_DATA_DISCOVERED
void uniffi_libgossip_fn_method_gossipscannerdelegate_peer_data_discovered(void*_Nonnull ptr, RustBuffer uuid, RustBuffer address_data, RustBuffer document_data, uint8_t peer_state, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_LOADCOLLECTIONDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_CLONE_LOADCOLLECTIONDELEGATE
void*_Nonnull uniffi_libgossip_fn_clone_loadcollectiondelegate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_LOADCOLLECTIONDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FREE_LOADCOLLECTIONDELEGATE
void uniffi_libgossip_fn_free_loadcollectiondelegate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_LOADCOLLECTIONDELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_INIT_CALLBACK_VTABLE_LOADCOLLECTIONDELEGATE
void uniffi_libgossip_fn_init_callback_vtable_loadcollectiondelegate(UniffiVTableCallbackInterfaceLoadCollectionDelegate* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_LOADCOLLECTIONDELEGATE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_METHOD_LOADCOLLECTIONDELEGATE_UPDATE
uint64_t uniffi_libgossip_fn_method_loadcollectiondelegate_update(void*_Nonnull ptr, RustBuffer state
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FUNC_CREATE_DUMMY_PROVIDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FUNC_CREATE_DUMMY_PROVIDER
void*_Nonnull uniffi_libgossip_fn_func_create_dummy_provider(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FUNC_UUID_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FUNC_UUID_FROM_BYTES
RustBuffer uniffi_libgossip_fn_func_uuid_from_bytes(uint8_t b1, uint8_t b2, uint8_t b3, uint8_t b4, uint8_t b5, uint8_t b6, uint8_t b7, uint8_t b8, uint8_t b9, uint8_t b10, uint8_t b11, uint8_t b12, uint8_t b13, uint8_t b14, uint8_t b15, uint8_t b16, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FUNC_WIDEID_TO_STRING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_FN_FUNC_WIDEID_TO_STRING
RustBuffer uniffi_libgossip_fn_func_wideid_to_string(RustBuffer wide_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_ALLOC
RustBuffer ffi_libgossip_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_libgossip_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_FREE
void ffi_libgossip_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUSTBUFFER_RESERVE
RustBuffer ffi_libgossip_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U8
void ffi_libgossip_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U8
void ffi_libgossip_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U8
void ffi_libgossip_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_libgossip_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I8
void ffi_libgossip_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I8
void ffi_libgossip_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I8
void ffi_libgossip_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I8
int8_t ffi_libgossip_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U16
void ffi_libgossip_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U16
void ffi_libgossip_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U16
void ffi_libgossip_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_libgossip_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I16
void ffi_libgossip_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I16
void ffi_libgossip_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I16
void ffi_libgossip_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I16
int16_t ffi_libgossip_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U32
void ffi_libgossip_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U32
void ffi_libgossip_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U32
void ffi_libgossip_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_libgossip_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I32
void ffi_libgossip_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I32
void ffi_libgossip_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I32
void ffi_libgossip_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I32
int32_t ffi_libgossip_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_U64
void ffi_libgossip_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_U64
void ffi_libgossip_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_U64
void ffi_libgossip_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_libgossip_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_I64
void ffi_libgossip_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_I64
void ffi_libgossip_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_I64
void ffi_libgossip_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_I64
int64_t ffi_libgossip_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_F32
void ffi_libgossip_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_F32
void ffi_libgossip_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_F32
void ffi_libgossip_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_F32
float ffi_libgossip_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_F64
void ffi_libgossip_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_F64
void ffi_libgossip_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_F64
void ffi_libgossip_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_F64
double ffi_libgossip_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_POINTER
void ffi_libgossip_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_POINTER
void ffi_libgossip_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_POINTER
void ffi_libgossip_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_libgossip_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_libgossip_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_libgossip_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_libgossip_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_libgossip_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_POLL_VOID
void ffi_libgossip_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_CANCEL_VOID
void ffi_libgossip_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_FREE_VOID
void ffi_libgossip_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_RUST_FUTURE_COMPLETE_VOID
void ffi_libgossip_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_FUNC_CREATE_DUMMY_PROVIDER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_FUNC_CREATE_DUMMY_PROVIDER
uint16_t uniffi_libgossip_checksum_func_create_dummy_provider(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_FUNC_UUID_FROM_BYTES
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_FUNC_UUID_FROM_BYTES
uint16_t uniffi_libgossip_checksum_func_uuid_from_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_FUNC_WIDEID_TO_STRING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_FUNC_WIDEID_TO_STRING
uint16_t uniffi_libgossip_checksum_func_wideid_to_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_BLOBS
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_BLOBS
uint16_t uniffi_libgossip_checksum_method_apphost_blobs(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_GLOBAL
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_GLOBAL
uint16_t uniffi_libgossip_checksum_method_apphost_global(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_SET_RESET_FLAG
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_SET_RESET_FLAG
uint16_t uniffi_libgossip_checksum_method_apphost_set_reset_flag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_SHUTDOWN
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_APPHOST_SHUTDOWN
uint16_t uniffi_libgossip_checksum_method_apphost_shutdown(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_START
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_START
uint16_t uniffi_libgossip_checksum_method_blegossipbroadcaster_start(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_STOP
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_STOP
uint16_t uniffi_libgossip_checksum_method_blegossipbroadcaster_stop(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_SET_DOCUMENT_DATA
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_SET_DOCUMENT_DATA
uint16_t uniffi_libgossip_checksum_method_blegossipbroadcaster_set_document_data(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_SET_ADDRESS_DATA
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_SET_ADDRESS_DATA
uint16_t uniffi_libgossip_checksum_method_blegossipbroadcaster_set_address_data(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_SET_PEER_STATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPBROADCASTER_SET_PEER_STATE
uint16_t uniffi_libgossip_checksum_method_blegossipbroadcaster_set_peer_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPSCANNER_START_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPSCANNER_START_SCANNING
uint16_t uniffi_libgossip_checksum_method_blegossipscanner_start_scanning(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPSCANNER_STOP_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPSCANNER_STOP_SCANNING
uint16_t uniffi_libgossip_checksum_method_blegossipscanner_stop_scanning(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPSCANNER_SET_DELEGATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLEGOSSIPSCANNER_SET_DELEGATE
uint16_t uniffi_libgossip_checksum_method_blegossipscanner_set_delegate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLOBDATADISPATCHER_HYDRATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLOBDATADISPATCHER_HYDRATE
uint16_t uniffi_libgossip_checksum_method_blobdatadispatcher_hydrate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLOBDATARESPONDER_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLOBDATARESPONDER_UPDATE
uint16_t uniffi_libgossip_checksum_method_blobdataresponder_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLOBDATARESPONDER_HASH
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_BLOBDATARESPONDER_HASH
uint16_t uniffi_libgossip_checksum_method_blobdataresponder_hash(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_DEVICEAPISERVICEPROVIDER_BLE_SCANNER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_DEVICEAPISERVICEPROVIDER_BLE_SCANNER
uint16_t uniffi_libgossip_checksum_method_deviceapiserviceprovider_ble_scanner(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_DEVICEAPISERVICEPROVIDER_BLE_BROADCASTER
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_DEVICEAPISERVICEPROVIDER_BLE_BROADCASTER
uint16_t uniffi_libgossip_checksum_method_deviceapiserviceprovider_ble_broadcaster(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_LOAD_NEARBY_PAYLOAD
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_LOAD_NEARBY_PAYLOAD
uint16_t uniffi_libgossip_checksum_method_global_load_nearby_payload(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SEND_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SEND_MESSAGE
uint16_t uniffi_libgossip_checksum_method_global_send_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_NAME
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_NAME
uint16_t uniffi_libgossip_checksum_method_global_set_name(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_PIC
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_PIC
uint16_t uniffi_libgossip_checksum_method_global_set_pic(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_SCANNING
uint16_t uniffi_libgossip_checksum_method_global_set_scanning(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_STATUS
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBAL_SET_STATUS
uint16_t uniffi_libgossip_checksum_method_global_set_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_NAME_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_NAME_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_name_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_PIC_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_PIC_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_pic_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_SCANNING_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_SCANNING_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_scanning_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_NEARBY_PROFILES_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_NEARBY_PROFILES_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_nearby_profiles_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_STATUS_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_STATUS_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_status_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_DEBUG_STATE_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_DEBUG_STATE_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_debug_state_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_ALL_MESSAGES_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_ALL_MESSAGES_UPDATED
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_all_messages_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_RECEIVED_ONE_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GLOBALVIEWMODEL_RECEIVED_ONE_MESSAGE
uint16_t uniffi_libgossip_checksum_method_globalviewmodel_received_one_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GOSSIPSCANNERDELEGATE_PEER_DATA_DISCOVERED
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_GOSSIPSCANNERDELEGATE_PEER_DATA_DISCOVERED
uint16_t uniffi_libgossip_checksum_method_gossipscannerdelegate_peer_data_discovered(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_LOADCOLLECTIONDELEGATE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_METHOD_LOADCOLLECTIONDELEGATE_UPDATE
uint16_t uniffi_libgossip_checksum_method_loadcollectiondelegate_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_CONSTRUCTOR_APPHOST_NEW
#define UNIFFI_FFIDEF_UNIFFI_LIBGOSSIP_CHECKSUM_CONSTRUCTOR_APPHOST_NEW
uint16_t uniffi_libgossip_checksum_constructor_apphost_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LIBGOSSIP_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_LIBGOSSIP_UNIFFI_CONTRACT_VERSION
uint32_t ffi_libgossip_uniffi_contract_version(void
    
);
#endif

